class NotFoundError(Exception):
    pass

class InternalError(Exception):
    pass

class FieldNotExistError(Exception):
    pass
